### ISSUE TITLE
How to give users access to the containerized bastion service? 

### ISSUE THREAD

**Issue by SujoySaha-work** [joshuamkite/terraform-aws-ssh-bastion-service#16]
I have been trying to setup this module in my VPC. I have 3 Users: dev-1, dev-2, dev-3 (all part of the same IAM-group, lets call it dev-access-group). Each user has uploaded their SSH public key to the AWS console in IAM/User/security section. Apart from this all users are part of the same group. 

What I am observing is that I am only able to login to the bastion host using admin and not with the dev-1, dev-2 users. Additionally, I had configured the bastion server to have a bastion-host-ssh-key for admin access, and I see that when I do:

ssh -i private_key_bastion_admin_ssh_public_key -p 2222 admin@elb.bastion-service.com (works fine!)

but 

ssh -i private_key_dev_1 -p 2222 dev-1@elb.bastion-service.com (Access denied/public key rejected)

Was curious if I am doing something wrong here? Any guidance would be very appreciated.

**Comment by SujoySaha-work** [comment]
Here is how I am using the terraform module:

provider "aws" {
  access_key = "access-key"
  secret_key = "some-key"
  region     = "us-east-1"
  profile = "customprofile"
  version = "~> 1.52.0"

}

module "ssh-bastion-service" {
  source  = "joshuamkite/ssh-bastion-service/aws"
  version = "4.4.0"
  aws_profile = "customprofile"
  aws_region = "us-east-1"
  vpc = "vpc-id"
  subnets_asg = ["6 subnets"]
  subnets_lb = ["6 subnets"]
  bastion_instance_type = "t2.medium"
  bastion_allowed_iam_group = "arn:aws:iam::ACCOUNT:group/dev-access-group"
  bastion_host_name= "TestSSHGateway"
  cidr_blocks_whitelist_host=["Whitelisted hosts"]
  asg_desired = "1"
  asg_max = "4"
  asg_min = "1"
  environment_name = "test"

  # insert the 3 required variables here
}

output "service-dns-name" {
    value = "${module.ssh-bastion-service.lb_dns_name}"
}

output "service-dns-entry" {
    value = "${module.ssh-bastion-service.service_dns_entry}"
}

**Comment by SujoySaha-work** [comment]
Made some progress here, documents do not mention that the ELB port to connect to is 22. Now ssh service is demanding password, despite no passphrase being set for users dev-1 and dev-2.

**Comment by SujoySaha-work** [comment]
Thanks! this was the exact problem I was facing. bastion_allowed_iam_group = "dev-access-group" solved this problem. I assumed I had to provide the ARN for the group, when I really should have just given the group name. 

One thing that I would mention is that, while it is amazing for users to be able to customize large portions of this module, for new users (like myself) it was difficult at first to understand what input fields would be required for a very simplistic use of the module. 

Also I believe it was not very clear that User public keys should be setup before the module is applied? It would be great to add a simple tutorial (I can submit a pull request to the Readme.md file with a "hello world" deployment) after which users can do a deep dive into the customizations that are suited for them? 

Once again thank you so much for helping me out with this!

**Comment by joshuamkite** [comment]
You are very welcome, I'm glad that you are now sorted. With Terraform AWS provider it is normal for 'name' to be something different to 'ARN', e.g. the [attributes for aws_iam_group](https://www.terraform.io/docs/providers/aws/r/iam_group.html).

I appreciate that there is a lot in this module and I am aware that in parts it is somewhat unorthodox. The customisable sections are  primarily intended for enterprise-level use, although I have seen some forks specify some additional packages for the container for example - not that this is the recommended method since you can supply your own userdata for that section!

That users need to upload their public ssh keys is covered under 

_Users should be aware that:_

_..._

_* They must manage their own ssh keys using the AWS interface(s), e.g. in the web console under **IAM/Users/Security credentials** and 'Upload SSH public key'._

 on line 133 in README.md. I appreciate that this is quite brief however._

From this conversation it would seem that the documentation is sufficiently long for people to miss important parts. Please do submit a pull request covering a simple deployment. I realise that I am missing a 'contributing.md' but I am very happy to accept external input, thank you for the suggestion.

Once again, glad that you are sorted.
