### ISSUE TITLE
 Port for GCP

### ISSUE THREAD

**Issue by djcoder100** [joshuamkite/terraform-aws-ssh-bastion-service#2]
Hi
How easy / hard would this be to port to GCP and run similar shorlived bastion host ?

**Comment by joshuamkite** [comment]
Sorry, only just seen this. Whilst it would theoretically be possible I don't know how much need there would be since you could just do [this](https://cloud.google.com/compute/docs/ssh-in-browser). Someone recently asked me a similar question in relation to OpenStack and I can give the same answer here:

The user-data section is largely reusable but the golang binary and the terraform plan proper is aws specific. You'd have to replace the former to work with something to accommodate whatever you're using for user authentication- getting a list of users and ssh public keys- and refactor the latter to work with whatever terraform provider or deployment tool you were using instead.
