### ISSUE TITLE
Logging to CloudWatch

### ISSUE THREAD

**Issue by jason-instacart** [joshuamkite/terraform-aws-ssh-bastion-service#24]
Thanks for this great module!

Can you give an example of the following?

```
... you can call this module from a plan specifiying your preferred logging solution, e.g. AWS cloudwatch.
```

**Comment by joshuamkite** [comment]
Thanks for your contribution!

I'm afraid that I cannot give a specific example because my current employer's solution is not open source. I can give a general description:

Everything in this Bastion solution works around systemd. The containers log to the host journal.  You can use the extra_user_data section to install an agent and config to read the host systemd journal and send it to your logging service.
