### ISSUE TITLE
unable to hit admin@host_address with key_pair

### ISSUE THREAD

**Issue by ghost** [joshuamkite/terraform-aws-ssh-bastion-service#63]
I am unable to access the node using the key pair associated with the instance. I am getting a key error, but I know the key is on the host, and the fingerprints of the uploaded key are the same as the one I have. Is accessing the host with the key pair not supported? I figured this might have something to do with the ssh server running in a docker container.

**Comment by joshuamkite** [comment]
The entire point of this project is to enable to use a key pair associated with an IAM user rather than an instance. The expectation is that in normal operation you would not have a key associated with the host itself at all. Yes it is possible to assign a key pair to the host, and security group rules to allow you to reach it, but that's not intended for production use.

It sounds like you are attempting to reach the containerised SSH server - which will be looking for your IAM SSH key - but using a key pair associated with the host. This won't work and nor should it. 

All of this is covered in the README

**Comment by ghost** [comment]
Ok, makes sense thanks.
